"""
Every rejected trade candidate gets exactly one of these reasons, in the order
the filter pipeline checks them (app/README.md §5). The pipeline stops at the
first failing gate.
"""
from enum import Enum


class NoTradeReason(str, Enum):
    SYMBOL_UNAVAILABLE = "NO_TRADE_SYMBOL_UNAVAILABLE"
    CONTRACT_UNAVAILABLE = "NO_TRADE_CONTRACT_UNAVAILABLE"
    STALE_DATA = "NO_TRADE_STALE_DATA"
    DATA_QUALITY_BELOW_THRESHOLD = "NO_TRADE_DATA_QUALITY_BELOW_THRESHOLD"
    MARKET_CLOSED = "NO_TRADE_MARKET_CLOSED"
    LOW_PAYOUT = "NO_TRADE_LOW_PAYOUT"
    BAD_REGIME = "NO_TRADE_BAD_REGIME"
    SIGNAL_INVALID = "NO_TRADE_SIGNAL_INVALID"
    LOW_PROBABILITY = "NO_TRADE_LOW_PROBABILITY"
    LOW_MODEL_CONFIDENCE = "NO_TRADE_LOW_MODEL_CONFIDENCE"
    NEGATIVE_EV = "NO_TRADE_NEGATIVE_EV"
    LOW_EDGE = "NO_TRADE_LOW_EDGE"
    RISK_LIMIT = "NO_TRADE_RISK_LIMIT"
    COOLDOWN = "NO_TRADE_COOLDOWN"
    RATE_LIMIT_EXCEEDED = "NO_TRADE_RATE_LIMIT_EXCEEDED"
    CORRELATED_EXPOSURE = "NO_TRADE_CORRELATED_EXPOSURE"
    API_UNHEALTHY = "NO_TRADE_API_UNHEALTHY"
    HIGH_LATENCY = "NO_TRADE_HIGH_LATENCY"
    HIGH_VOLATILITY = "NO_TRADE_HIGH_VOLATILITY"
